# Generated by Django 5.0.4 on 2024-04-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('cadastro_paciente', '0006_alter_cadastropaciente_data_nascimento'),
        ('login_terapeuta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('_idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_paciente.cadastropaciente')),
                ('_idTerapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_terapeuta.loginterapeuta')),
            ],
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
