# Generated by Django 5.0.4 on 2024-04-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginTerapeuta",
            fields=[
                ("idTerapeuta", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("senha", models.CharField(max_length=100)),
            ],
        ),
    ]
