# Generated by Django 5.0.4 on 2024-04-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("login_terapeuta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastroPaciente",
            fields=[
                ("idPaciente", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(max_length=14)),
                ("rg", models.CharField(max_length=20)),
                ("celular", models.CharField(max_length=20)),
                ("endereco", models.TextField()),
                ("nacionalidade", models.CharField(max_length=100)),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("solteiro", "Solteiro(a)"),
                            ("casado", "Casado(a)"),
                            ("divorciado", "Divorciado(a)"),
                            ("viuvo", "Viúvo(a)"),
                            ("uniao_estavel", "União Estável"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("profissao", models.CharField(max_length=100)),
                (
                    "idTerapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login_terapeuta.loginterapeuta",
                    ),
                ),
            ],
        ),
    ]
