# Generated by Django 5.0.4 on 2024-04-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_paciente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastropaciente",
            name="convenio",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
