# Generated by Django 5.0.4 on 2024-04-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_paciente", "0003_alter_cadastropaciente_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastropaciente",
            name="celular",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="convenio",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="endereco",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="nacionalidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="profissao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cadastropaciente",
            name="rg",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
