# Generated by Django 5.0.4 on 2024-04-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_paciente", "0004_alter_cadastropaciente_celular_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastropaciente",
            name="idTerapeuta",
        ),
    ]
