# Generated by Django 5.0.4 on 2024-04-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0005_remove_cadastropaciente_idterapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropaciente',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
