# Generated by Django 5.0.4 on 2024-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0006_alter_cadastropaciente_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropaciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
